name: erarobot

source:
  type: github
  repository: https://github.com/IamDuru/ERAROBOT.git
  branch: main  # or the branch your worker code is on

# Define the services (like a worker or web service) in your deployment
services:
  - name: python-worker
    type: worker  # Use worker since it's not a web app
    env: python
    instance:
      plan: nano  # Choose the instance type, adjust based on your workload
    build:
      commands:
        - pip install -r requirements.txt  # Install dependencies
    run:
      command: python3 -m ERA  # Replace with your worker script name

